kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: dockerconfigjson-github-com
stringData:
  # This is to setup the authentication to Github Container Registry
  # Replace <auth_token> by "$username:$access-token" parsed in base 64
  # Then run kubectl apply -f ./secret.yml
  .dockerconfigjson: '{"auths":{"ghcr.io":{"auth":"<auth_token>"}}}'
